#!/bin/bash
help_fun() {
    echo "Usage: desktop-file [OPTIONS]"
    echo "Options:"
    echo "--list : List all desktop files"
    echo "--delete [name] : Delete a desktop file"
    echo "--new : Create a new desktop file args: --path <path>"
    echo "--help : Show this help message"
}

create_desktop_file() {
    local desktop_file="$1"
    local exepath="$2"
    local iconpath="$3"
    local appname="$4"

    cat <<EOL >"$desktop_file"
    [Desktop Entry]
    Type=Application
    Exec=$(realpath "$exepath")
    Icon=$(realpath "$iconpath")
    Terminal=false
    Name=${appname}
EOL
}

# if no args are provided, show help
if [ $# -eq 0 ]; then
    help_fun
    exit 0
fi

# Check if the user wants to list all desktop files
if [ "$1" == "--list" ]; then
    ls ~/.local/share/applications/*.desktop
    exit 0
fi

# Check if the user wants to delete a desktop files 
#like --delete  a b c
#delete multiple files
if [ "$1" == "--delete" ]; then
    shift
    while (( "$#" )); do
        rm ~/.local/share/applications/"$1".desktop
        shift
    done
    exit 0
fi

# Check if the user wants help
if [ "$1" == "--help" ]; then
    help_fun
fi

# Check if the user wants to create a new desktop file
if [ "$1" == "--new" ]; then
    # Get input from the user
    default_path=~/.local/share/applications/
    # check --path argument
    if [ "$2" == "--path" ]; then
        default_path="$(realpath "$3")/"
    fi
    echo ------- .desktop file generator ----------
    read -p "Enter app name: " appname
    desktop_file="${appname}.desktop"

    # Check if the desktop file already exists
    if [ -e "$desktop_file" ]; then
        read -p "Desktop file already exists. Do you want to overwrite it? (y/n): " overwrite
        if [ "$overwrite" != "y" ]; then
            echo "Aborted. Desktop file not created."
            exit 1
        fi
    fi

    read -p "Enter icon path: " iconpath
    read -p "Enter executable path: " exepath

    # Create the .desktop file
    create_desktop_file "$desktop_file" "$exepath" "$iconpath" "$appname"

    chmod +x "$desktop_file"
    echo "path" $default_path
    echo "desktop_file" $desktop_file
    cp "$desktop_file" "$default_path"
    echo "Desktop file '$desktop_file' created successfully. to path '$default_path'"
    exit 0
fi
