#!/bin/bash
# Check if the user provided at least one argument
if [ $# -lt 1 ]; then
  echo "Usage: run app_name arg1 arg2 arg3 ..."
  exit 1
fi

# Get the first argument which is the application name
app_name=$1

# Shift the arguments to the left, effectively removing the first argument (app_name)
shift

# Run the application along with its arguments
"$app_name" "$@" >/dev/null 2>&1 &